process.env.POSTGRES_USER="creativecode"
process.env.POSTGRES_PASSWORD="creativecode"
process.env.DB_USER="creativecode"
process.env.DB_PASSWORD="creativecode"
process.env.DB_HOST="postgres"
process.env.DB_PORT="5432"
process.env.DB_NAME="creativecode"