version: "3"
services:
  app:
    build: .
    depends_on:
      - postgres
    ports:
      - "3000:3000"
      - "9229:9229"
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
  postgres:
    image: postgres
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - APP_DB_USER
      - APP_DB_PASS
      - APP_DB_NAME
    volumes:
    - ./db:/docker-entrypoint-initdb.d/
